# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true
#encoding: UTF-8


# edit here to achieve your personal greatness
url: http://pablofbaez.github.io
baseurl: /
title: Pablo Báez
author: Pablo Báez
description: Personal website and curriculum vitae.
avatar: profile3.png
email: pablobaez@ug.uchile.cl  
github: pablofbaez # username
twitter: pablofbaez
#linkedin: sctyner
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-153785612-1


# needed for travis-ci build
exclude: 
  - [vendor]
  - Gemfile
  - Gemfile.lock

